### ISSUE TITLE
sblgnt_tei_capitains.xml misses last verse in chapter

### ISSUE THREAD

**Issue by pharos-alexandria** [jjmccollum/sblgnt-tei#1]
The last verse in each chapter (for example Mt 1:25) is missing from the file (but not from sblgnt_tei.xml).

(I've corrected it in my version at https://github.com/PatristicTextArchive/pta_data/tree/public/data/pta9999, but also did some other changes necessary for PTA, so unfortunately I cannot just do a pull request for your file here, sorry!)

**Comment by jjmccollum** [comment]
@pharos-alexandria Thanks for bringing this to my attention! I must have forgotten a necessary line of code in the script for converting the standard TEI XML file to the CapiTainS version. I wrote a quick script to copy over the missing verses, and it looks like the counts of verse `div`/`milestone` elements now match at 7927. My apologies for the additional work you had to do to restore the missing verses for your version!

**Comment by pharos-alexandria** [comment]
No problem, @jjmccollum, your original file helped me a lot to get me going! Thanks again!
